# https://docusaurus.io/docs/en/publishing.html#using-circle-ci-20
version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "nating@users.noreply.github.com"
            git config --global user.name "nating"
            echo "machine github.com login nating password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=nating yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website
